TFL_APP_KEY = "c0b46040846a4a4399f8b67958db4610"
CONSUMER_KEY = "aSu6KXTHOrwBAaxgCMGIgV9MkQvHTYol0GAXUXuz2pYtOpEr"
CONSUMER_SECRET = "2KaGSYEI5VCh1Lz6SwsJ62vGpGXOVyzOSGW7R2Inv0y11aM6QtLozogZxA7u3pL2"
